rules: []
rulesConfigs: []
hooks: []
pages: []
resourceServers: []
clients:
  - name: API Explorer Application
    app_type: non_interactive
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: Default App
    callbacks: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
  - name: DeployCLI
    app_type: non_interactive
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: DeployCLI SPA Test
    allowed_clients: []
    allowed_logout_urls:
      - http://localhost:3000
    app_type: spa
    callbacks:
      - http://localhost:3000
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - http://localhost:3000
  - name: TEST PRIVATE KEY JWT
    addons: {}
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    client_authentication_methods:
      private_key_jwt:
        credentials:
          - id: cred_16HH7syNcJfYpXkj7NtgPg
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - API Explorer Application
      - Default App
      - DeployCLI
      - DeployCLI SPA Test
      - TEST PRIVATE KEY JWT
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      passwordPolicy: good
      passkey_options:
        challenge_ui: both
        local_enrollment_enabled: true
        progressive_enrollment_enabled: true
      strategy_version: 2
      authentication_methods:
        passkey:
          enabled: false
        password:
          enabled: true
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - API Explorer Application
      - Default App
      - DeployCLI
      - DeployCLI SPA Test
      - TEST PRIVATE KEY JWT
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - en
  flags:
    allow_legacy_delegation_grant_types: false
    allow_legacy_ro_grant_types: true
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  oidc_logout:
    rp_logout_end_session_endpoint_discovery: true
  sandbox_version: '18'
emailProvider: {}
emailTemplates: []
clientGrants:
  - client_id: API Explorer Application
    audience: ##AUDIENCE##
    scope:
      - read:client_grants
      - create:client_grants
      - delete:client_grants
      - update:client_grants
      - read:users
      - update:users
      - delete:users
      - create:users
      - read:users_app_metadata
      - update:users_app_metadata
      - delete:users_app_metadata
      - create:users_app_metadata
      - read:user_custom_blocks
      - create:user_custom_blocks
      - delete:user_custom_blocks
      - create:user_tickets
      - read:clients
      - update:clients
      - delete:clients
      - create:clients
      - read:client_keys
      - update:client_keys
      - delete:client_keys
      - create:client_keys
      - read:connections
      - update:connections
      - delete:connections
      - create:connections
      - read:resource_servers
      - update:resource_servers
      - delete:resource_servers
      - create:resource_servers
      - read:device_credentials
      - update:device_credentials
      - delete:device_credentials
      - create:device_credentials
      - read:rules
      - update:rules
      - delete:rules
      - create:rules
      - read:rules_configs
      - update:rules_configs
      - delete:rules_configs
      - read:hooks
      - update:hooks
      - delete:hooks
      - create:hooks
      - read:actions
      - update:actions
      - delete:actions
      - create:actions
      - read:email_provider
      - update:email_provider
      - delete:email_provider
      - create:email_provider
      - blacklist:tokens
      - read:stats
      - read:insights
      - read:tenant_settings
      - update:tenant_settings
      - read:logs
      - read:logs_users
      - read:shields
      - create:shields
      - update:shields
      - delete:shields
      - read:anomaly_blocks
      - delete:anomaly_blocks
      - update:triggers
      - read:triggers
      - read:grants
      - delete:grants
      - read:guardian_factors
      - update:guardian_factors
      - read:guardian_enrollments
      - delete:guardian_enrollments
      - create:guardian_enrollment_tickets
      - read:user_idp_tokens
      - create:passwords_checking_job
      - delete:passwords_checking_job
      - read:custom_domains
      - delete:custom_domains
      - create:custom_domains
      - update:custom_domains
      - read:email_templates
      - create:email_templates
      - update:email_templates
      - read:mfa_policies
      - update:mfa_policies
      - read:roles
      - create:roles
      - delete:roles
      - update:roles
      - read:prompts
      - update:prompts
      - read:branding
      - update:branding
      - delete:branding
      - read:log_streams
      - create:log_streams
      - delete:log_streams
      - update:log_streams
      - create:signing_keys
      - read:signing_keys
      - update:signing_keys
      - read:limits
      - update:limits
      - create:role_members
      - read:role_members
      - delete:role_members
      - read:entitlements
      - read:attack_protection
      - update:attack_protection
      - read:organizations_summary
      - create:authentication_methods
      - read:authentication_methods
      - update:authentication_methods
      - delete:authentication_methods
      - read:organizations
      - update:organizations
      - create:organizations
      - delete:organizations
      - create:organization_members
      - read:organization_members
      - delete:organization_members
      - create:organization_connections
      - read:organization_connections
      - update:organization_connections
      - delete:organization_connections
      - create:organization_member_roles
      - read:organization_member_roles
      - delete:organization_member_roles
      - create:organization_invitations
      - read:organization_invitations
      - delete:organization_invitations
      - read:scim_config
      - create:scim_config
      - update:scim_config
      - delete:scim_config
      - create:scim_token
      - read:scim_token
      - delete:scim_token
      - delete:phone_providers
      - create:phone_providers
      - read:phone_providers
      - update:phone_providers
      - delete:phone_templates
      - create:phone_templates
      - read:phone_templates
      - update:phone_templates
      - create:encryption_keys
      - read:encryption_keys
      - update:encryption_keys
      - delete:encryption_keys
      - read:sessions
      - delete:sessions
      - read:refresh_tokens
      - delete:refresh_tokens
      - create:self_service_profiles
      - read:self_service_profiles
      - update:self_service_profiles
      - delete:self_service_profiles
      - create:sso_access_tickets
      - delete:sso_access_tickets
      - read:forms
      - update:forms
      - delete:forms
      - create:forms
      - read:flows
      - update:flows
      - delete:flows
      - create:flows
      - read:flows_vault
      - read:flows_vault_connections
      - update:flows_vault_connections
      - delete:flows_vault_connections
      - create:flows_vault_connections
      - read:flows_executions
      - delete:flows_executions
      - read:connections_options
      - update:connections_options
      - read:self_service_profile_custom_texts
      - update:self_service_profile_custom_texts
      - create:network_acls
      - update:network_acls
      - read:network_acls
      - delete:network_acls
      - delete:vdcs_templates
      - read:vdcs_templates
      - create:vdcs_templates
      - update:vdcs_templates
      - create:custom_signing_keys
      - read:custom_signing_keys
      - update:custom_signing_keys
      - delete:custom_signing_keys
      - read:federated_connections_tokens
      - delete:federated_connections_tokens
      - read:client_credentials
      - create:client_credentials
      - update:client_credentials
      - delete:client_credentials
      - read:organization_client_grants
      - create:organization_client_grants
      - delete:organization_client_grants
  - client_id: TEST PRIVATE KEY JWT
    audience: https://mbh-paid-2.us.auth0.com/api/v2/
    scope:
      - read:client_grants
      - create:client_grants
      - delete:client_grants
      - update:client_grants
      - read:users
      - update:users
      - delete:users
      - create:users
      - read:users_app_metadata
      - update:users_app_metadata
      - delete:users_app_metadata
      - create:users_app_metadata
      - read:user_custom_blocks
      - create:user_custom_blocks
      - delete:user_custom_blocks
      - create:user_tickets
      - read:clients
      - update:clients
      - delete:clients
      - create:clients
      - read:client_keys
      - update:client_keys
      - delete:client_keys
      - create:client_keys
      - read:connections
      - update:connections
      - delete:connections
      - create:connections
      - read:resource_servers
      - update:resource_servers
      - delete:resource_servers
      - create:resource_servers
      - read:device_credentials
      - update:device_credentials
      - delete:device_credentials
      - create:device_credentials
      - read:rules
      - update:rules
      - delete:rules
      - create:rules
      - read:rules_configs
      - update:rules_configs
      - delete:rules_configs
      - read:hooks
      - update:hooks
      - delete:hooks
      - create:hooks
      - read:actions
      - update:actions
      - delete:actions
      - create:actions
      - read:email_provider
      - update:email_provider
      - delete:email_provider
      - create:email_provider
      - blacklist:tokens
      - read:stats
      - read:insights
      - read:tenant_settings
      - update:tenant_settings
      - read:logs
      - read:logs_users
      - read:shields
      - create:shields
      - update:shields
      - delete:shields
      - read:anomaly_blocks
      - delete:anomaly_blocks
      - update:triggers
      - read:triggers
      - read:grants
      - delete:grants
      - read:guardian_factors
      - update:guardian_factors
      - read:guardian_enrollments
      - delete:guardian_enrollments
      - create:guardian_enrollment_tickets
      - read:user_idp_tokens
      - create:passwords_checking_job
      - delete:passwords_checking_job
      - read:custom_domains
      - delete:custom_domains
      - create:custom_domains
      - update:custom_domains
      - read:email_templates
      - create:email_templates
      - update:email_templates
      - read:mfa_policies
      - update:mfa_policies
      - read:roles
      - create:roles
      - delete:roles
      - update:roles
      - read:prompts
      - update:prompts
      - read:branding
      - update:branding
      - delete:branding
      - read:log_streams
      - create:log_streams
      - delete:log_streams
      - update:log_streams
      - create:signing_keys
      - read:signing_keys
      - update:signing_keys
      - read:limits
      - update:limits
      - create:role_members
      - read:role_members
      - delete:role_members
      - read:entitlements
      - read:attack_protection
      - update:attack_protection
      - read:organizations_summary
      - create:authentication_methods
      - read:authentication_methods
      - update:authentication_methods
      - delete:authentication_methods
      - read:organizations
      - update:organizations
      - create:organizations
      - delete:organizations
      - create:organization_members
      - read:organization_members
      - delete:organization_members
      - create:organization_connections
      - read:organization_connections
      - update:organization_connections
      - delete:organization_connections
      - create:organization_member_roles
      - read:organization_member_roles
      - delete:organization_member_roles
      - create:organization_invitations
      - read:organization_invitations
      - delete:organization_invitations
      - read:scim_config
      - create:scim_config
      - update:scim_config
      - delete:scim_config
      - create:scim_token
      - read:scim_token
      - delete:scim_token
      - delete:phone_providers
      - create:phone_providers
      - read:phone_providers
      - update:phone_providers
      - delete:phone_templates
      - create:phone_templates
      - read:phone_templates
      - update:phone_templates
      - create:encryption_keys
      - read:encryption_keys
      - update:encryption_keys
      - delete:encryption_keys
      - read:sessions
      - delete:sessions
      - read:refresh_tokens
      - delete:refresh_tokens
      - create:self_service_profiles
      - read:self_service_profiles
      - update:self_service_profiles
      - delete:self_service_profiles
      - create:sso_access_tickets
      - delete:sso_access_tickets
      - read:forms
      - update:forms
      - delete:forms
      - create:forms
      - read:flows
      - update:flows
      - delete:flows
      - create:flows
      - read:flows_vault
      - read:flows_vault_connections
      - update:flows_vault_connections
      - delete:flows_vault_connections
      - create:flows_vault_connections
      - read:flows_executions
      - delete:flows_executions
      - read:connections_options
      - update:connections_options
      - read:self_service_profile_custom_texts
      - update:self_service_profile_custom_texts
      - create:network_acls
      - update:network_acls
      - read:network_acls
      - delete:network_acls
      - delete:vdcs_templates
      - read:vdcs_templates
      - create:vdcs_templates
      - update:vdcs_templates
      - create:custom_signing_keys
      - read:custom_signing_keys
      - update:custom_signing_keys
      - delete:custom_signing_keys
      - read:federated_connections_tokens
      - delete:federated_connections_tokens
      - create:user_attribute_profiles
      - read:user_attribute_profiles
      - update:user_attribute_profiles
      - delete:user_attribute_profiles
      - read:client_credentials
      - create:client_credentials
      - update:client_credentials
      - delete:client_credentials
      - read:organization_client_grants
      - create:organization_client_grants
      - delete:organization_client_grants
      - read:event_streams
      - create:event_streams
      - update:event_streams
      - delete:event_streams
      - read:event_deliveries
      - update:event_deliveries
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  templates: []
phoneProviders: []
prompts:
  customText: {}
  partials: {}
  universal_login_experience: new
actions: []
triggers: {}
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
      pre-change-password:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
customDomains:
  - domain: auth.mbh-dse-2.com
    primary: true
    status: failed
    tls_policy: recommended
    type: auth0_managed_certs
    verification:
      methods:
        - name: CNAME
          record: mbh-paid-2-cd-l72bg2ghpkgkp1jb.edge.tenants.us.auth0.com
          domain: auth.mbh-dse-2.com
themes: []
forms: []
flows: []
flowVaultConnections: []
selfServiceProfiles: []
